# This is a basic workflow for APIOps

name: Dad Jokes API Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dadjokes-api:
    runs-on: ubuntu-latest    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create temp dirs
        run: |
          mkdir ./spec
          mkdir ./spec-backup

      - name: Backup Insomnia Spec
        run: |
          cp ./.insomnia/ApiSpec/*.yml ./spec-backup
          ls ./spec-backup 

      - name: Install Dev Tools (NodeJS)
        uses: actions/setup-node@v1

      - name: Install Dev Tools (Deck)
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.6.0/deck_1.6.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/ 

      - name: Install Dev Tools (Inso)
        run: npm install -g insomnia-inso@2.3.0

      - name: Prepare Upstream URL for Kong declarative config
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./.insomnia/ApiSpec/*.yml"]'
        env:
          UPSTREAM_SERVER_URL: '${{ secrets.UPSTREAM_SERVER_URL }}'
      
      - name: Generate Kong declarative config
        run: |
          inso generate config dadjokes-api --type declarative --tags $TAG --output kong.yaml 
          cat kong.yaml
        env:
          TAG: dadjokes-api
      
      - name: Replace API Key in workspace config
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./workspaces/dadjokes/dadjokes.yaml"]'
        env:
          ALICE_API_KEY: '${{ secrets.ALICE_API_KEY }}'

      - name: Replace Kong Admin Url in workspace config
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./workspaces/dadjokes/cli.conf.yaml"]'
        env:
          KONG_ADMIN_URL: '${{ secrets.KONG_ADMIN_ADDR }}'          

      - name: Check connectivity to Kong Control Plane
        run: |
          deck ping --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} --tls-skip-verify
      
      - name: Validate the Declarative Config File
        run: |
          deck validate --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} -s kong.yaml -s ./workspaces/dadjokes/dadjokes.yaml --tls-skip-verify
     
      - name: Deploy to Kong
        run: deck sync --workspace ${{ secrets.KONG_WORKSPACE }} --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} -s kong.yaml -s ./workspaces/dadjokes/dadjokes.yaml --tls-skip-verify

      - name: Run test suites
        run: inso run test dadjokes-api-test -e ${{ env.TARGET_ENVIRONMENT }} --ci
        env:
          TARGET_ENVIRONMENT: AWS

  publish-dadjokes-api-to-portal:
    name: Publish Dad Jokes API to Dev Portal
    needs: deploy-dadjokes-api
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dev Tools (NodeJS)
        uses: actions/setup-node@v1

      - name: Install Dev Tools (Inso + Portal CLI)
        run: npm install -g insomnia-inso@2.3.0 kong-portal-cli@3.1.0 
     
      - name: Prepare Server URL for Spec
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./.insomnia/ApiSpec/*.yml"]'
        env:
          UPSTREAM_SERVER_URL: '${{ secrets.KONG_PROXY_ADDR }}'    
          
      - name: Enable Dev Portal on Workspace  
        run: |
          portal enable -D ${{ secrets.KONG_WORKSPACE }}
                
      - name: Deploy to Dev Portal
        run: |          
          inso export spec dadjokes-api --output workspaces/${{ secrets.KONG_WORKSPACE }}/specs/dadjokes.yaml
          portal deploy -D --preserve ${{ secrets.KONG_WORKSPACE }}
        env:
          KONG_ADMIN_URL: ${{ secrets.KONG_ADMIN_ADDR }}         