# This is a basic workflow for APIOps

name: Dad Jokes API Pull Request Validation

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate-dadjokes-api:

    name: Validate Dad Jokes API to Gateway and Dev Portal
    runs-on: ubuntu-latest
    steps:
      - name: (Step 01) Checkout Repository
        uses: actions/checkout@v3

      - name: (Step 02) Backup Specs
        run: |
          mkdir ./spec
          mkdir ./spec-backup
          cp ./.insomnia/ApiSpec/*.yml ./spec-backup
          ls ./spec-backup 
     
      - name: (Step 03) Install NodeJS
        uses: actions/setup-node@v1

      - name: (Step 04) Install Dev Tools (Deck + Inso)
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.6.0/deck_1.6.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/ 
          npm install -g insomnia-inso@2.3.0
     
      - name: (Step 05) Run API Linting Rules
        run: inso lint spec dadjokes-api
        
      - name: (Step 06) Inject Upstream URL into APISpec
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./.insomnia/ApiSpec/*.yml"]'
        env:
          UPSTREAM_SERVER_URL: '${{ secrets.UPSTREAM_SERVER_URL }}'
      
      - name: (Step 07) Generate Kong declarative config
        run: |
          inso generate config dadjokes-api --type declarative --tags $TAG --output kong.yaml 
          cat kong.yaml
        env:
          TAG: dadjokes-api
      
      - name: (Step 08) Inject secrets into declaritive config
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./workspaces/dadjokes/dadjokes.yaml"]'
        env:
          ALICE_API_KEY: '${{ secrets.ALICE_API_KEY }}'

      - name: (Step 09) Inject Kong Workspace settings
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./workspaces/dadjokes/cli.conf.yaml"]'
        env:
          KONG_ADMIN_URL: '${{ secrets.KONG_ADMIN_ADDR }}'             
          
      - name: (Step 10) Check Kong Control Plane connectivity
        run: |
          deck ping --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} --tls-skip-verify
      
      - name: (Step 11) Validate Kong declarative config
        run: |
          deck validate --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} -s kong.yaml -s ./workspaces/dadjokes/dadjokes.yaml --tls-skip-verify
          
      - name: (Step 12) Detect Kong config drift
        run: |
          deck diff --kong-addr ${{ secrets.KONG_ADMIN_ADDR }} -s kong.yaml -s ./workspaces/dadjokes/dadjokes.yaml -w ${{ secrets.KONG_WORKSPACE }} --tls-skip-verify